root: ./data
tasktag: NEXTITEM

alpha: 0.05
num_states: 30
maxlen: 1024

hidden_size: 256
num_hidden_layers: 4
num_attention_heads: 2

epochs: 5001
batch_size: 128
gradient_accumulation_steps: 4
optimizer: AdamW
lr: 3.e-4
weight_decay: 0.1